### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shochan614** [shochan614/furima-30636#9]
#url
https://furima-30636.herokuapp.com/

#Basic認証のIDとパスワード
id:furima 
pw:1027

#出品者用のメールアドレスとパスワード
email:ya@1
pw:1aaaaa
#購入者用のメールアドレスとパスワード
email:2b@b
pw:1aaaaa
#購入用カードの番号・期限・セキュリティコード
番号:4242424242424242
m/y:12/20
cvc:123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
